### ISSUE TITLE
Enable control click and shift click during directory selection.

### ISSUE THREAD

**Issue by drkludge** [osmottawa/OSVUploadr#10]
I cannot use control click nor shift click to select several directories to upload.  Is there anyway that this feature can be enabled or is this a Java Swing limitation?  Currently, I have to select a directory and the save button for each directory that I want to upload.  A work around that I can think of is to create a directory and moving the image directories into that new directory.  Then I can pick the one new directory but upload many directories.

**Comment by james2432** [comment]
I can look into it. I added a prompt to add all subfolders in a folder to help with this problem.

**Comment by james2432** [comment]
shift+click and ctrl+click will work now. the adding of all folders only is asked if you select a folder

**Comment by drkludge** [comment]
I can confirm that release https://github.com/osmottawa/OSVUploadr/releases/tag/v0.1.2.2.2-ALPHA adds the ability to shift+click and ctrl+click functionality.  Thank you.
