### ISSUE TITLE
Provide Localization Examples In Readme.

### ISSUE THREAD

**Issue by drkludge** [osmottawa/OSVUploadr#11]
[Issue 7](https://github.com/osmottawa/OSVUploadr/issues/7) explains the problem with calling the localization settings.

1.The readme.md needs to be updated with the localization information and supported language calls.  It just makes it easier to get going.
2.I believe you could create a new release and say that the software is now beta.

How to use

To start the application you need the java runtime environment(JRE) version 1.8+. To launch it you can double click the .jar file. If that doesn't work, running it via the command line via **java -jar [jar file path]/OSVUploadr.jar will.**

**Comment by james2432** [comment]
Until I get multi-threading/Upload button unstuck it will remain as alpha software

**Comment by james2432** [comment]
Updated readme to give examples

**Comment by drkludge** [comment]
The changes to the readme file look good.  Thanks.
