### ISSUE TITLE
If no sub-folders still add the root folder

### ISSUE THREAD

**Issue by Stalfur** [osmottawa/OSVUploadr#17]
I was trying to get this to work for my Virb images and it didn't work until I realised I should not click "Yes" for subdirectories if there was no subdirectory. No folder gets added if I say "yes" to subdirectory when there is no.

**Comment by james2432** [comment]
Virb organizes trip images in multiple subfolders, to upload as one sequence, they should be in the same folder. If you took 5 trips, you'd have 5 folders ideally with their respective images. The add all subfolders was a shortcut incase you have multiple folders and dont want to add each individually. You can also select multiple with shift and it wont prompt you for it

**Comment by Stalfur** [comment]
A single directory on my VIRB can contain different trips. Basically it just counts to 1000 per folder and then starts a new one. If I take several short trips they can be in one folder with the last trip partially in another folder.

So what I'm doing is in each folder creating a subfolder if it is more than 1 trip/sequence inside it. Opening up 20.000 images in 20 folders from 80 different trips is probably not going to go great?

**Comment by james2432** [comment]
I'm aware how the virb takes photos, i have 4. You need to put each trip into one folder, not segregated into hundreds. I'm planning on adding an option to autoorganize photos per tripbased on time taken/distance. Until then photos need to be organized manually

**Comment by james2432** [comment]
Are you using Linux? There seems to be the issue (Linux only) that you need to highlight the folder instead of entering it.

**Comment by Stalfur** [comment]
Windows 10

**Comment by james2432** [comment]
So, if you have a folder that has the photos:
C:\Photos\
and you go into the photo folder via the browse window does it add:
C:\Photos\Photos 
To the list?
