### ISSUE TITLE
OSV Credentials via environment variables or CLI

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/OSVUploadr#2]
Could it be possible to enter your OSV credentials via CLI.

``` bash
$ java -jar OSVUploadr.jar --username <USER> --password <PASS>
```

Or via environment variables.

``` bash
$ export OSV_USERNAME="<USER>"
$ export OSV_PASSWORD="<PASSWORD>"
```

**Comment by james2432** [comment]
You can now authenticate via GUI. You no longer have to login via a browser, but the option is still there.

**Comment by DenisCarriere** [comment]
Woot!
