### ISSUE TITLE
Releases are not working.

### ISSUE THREAD

**Issue by drkludge** [osmottawa/OSVUploadr#5]
I tried your release page here https://github.com/osmottawa/OSVUploadr/releases.

- The gz archive downloads.
- The source archive downloads.
- I receive the following message/error when I try the binary zip download.
I take it that this zip file has the jar file for the `java -jar [jar file path]/OSVUploadr.jar` command line?

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
releases/64803647/e32345ba-8626-11e6-860c-f8eaebe4b4f6.zip
</Key>
<RequestId>98CAFADB373BCDC0</RequestId>
<HostId>
Gvs9R25I6AVhkOE3K7MuKlr8tiz7u1PZViLZUz4bypdnu8heYBQEYSU0EYvGUNNi6JwOQBZS0fs=
</HostId>
</Error>
```

**Comment by james2432** [comment]
The only "gz" is Source code (tar.gz) which you need to compile...
What you want is:  OSVUploadr.zip.
You need to extract it, then run it.

**Comment by drkludge** [comment]
Yep! OSVUploadr.zip cannot be downloaded to extract it.

**Comment by james2432** [comment]
Ah. I think I know why... I'll compile it tomorrow (our github group was deleted by accident and was restored recently)

**Comment by drkludge** [comment]
Thanks.

**Comment by james2432** [comment]
Version 0.1.2.2.1 binary should work now (zip)
