### ISSUE TITLE
Mapillary Directories Supported.  Change Readme.md file.

### ISSUE THREAD

**Issue by drkludge** [osmottawa/OSVUploadr#8]
I Vimed the Bundle_fr.properties and Bundle.properties together.  I was able to switch between the two files in order to read the French screen prompts.  [Pyuploader](http://www.openstreetview.org/details/18167/1) created these images.  (I haven't been able to get the application to work for awhile.)  [I used OSVUploader](http://www.openstreetview.org/details/27701/34) for this sequence.

Adding the `count_file.txt` and `sequence_file.txt` to the directory is a nice touch.  That helps keep track of which directories that I have uploaded.

Since I have saved all my Mapillary images in the original sequence directory, `2016_10_28_14_23_05_524___Mapillary`, I was able to use the application.  Hence, unless there is some other problem, I think that you could update the README.md file that Mapillary sequences are supported.  The language issue and threading are the top two issues right now.  The upload was slow but since I ran the application from a command prompt I could watch all the details pass by.  There is a bunch of useful information!

```
README.md
Known issues
...
Upload process is not threaded, so the upload button will look frozen until it finishes the upload.
...
Application is only for action cameras. I will eventually incorporate images/videos taken from the APP.

```

**Comment by james2432** [comment]
Well seeing as mapillary can be video(.mp4), i'd rather not put "mapillary", but I can put any geotagged image with correct original timestamp info.

**Comment by james2432** [comment]
Also the count and sequence are ment to be interchangable with the python scripts supplied by OSV

**Comment by james2432** [comment]
p.s. if you want to get around speed issue you can launch multiple instances of OSVUploadr. This is for different folders and not the same folders. It's the poor-mans multi-threading but works just as well.
